Test
Mornilius/QA-bookvoed pull request #1
Opened 2023-12-25 15:41 UTC by Mornilius

2023-12-25 16:21 UTC, Sanjaneo commented
так же при каждом ПРе нужно прикладывать прогон тестов которые затрагиваешь (достаточно просто скрин показать из идеи пока что). Если тебе напихали комментов и ты их правил в рамках ПРа, то нужно свежий отчет прикладывать что после правок все работает

2023-12-25 16:24 UTC, Sanjaneo requested changes

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static final By MAIN_WINDOW = By.xpath("//*[@id='bottom_action']/div");
по поводу названий. У тебя это константы локаторов, лучше так и прописывать в конце названий LOCATOR (кто-то требует, кто-то закрывает глаза. Но я считаю, что у всего должно быть максимально понятное название переменной. Если это локатор то так и пиши, если это меседж для ассерта, то так и пиши в конце MESSAGE)

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static final By LOG_AND_REGISTRATION = By.xpath("//*[@id='bottom_action-bac-phone_auth_form']/form/h2");
тоже не принципиальный момент, но мне кажется что так лучше. У тебя ряд локаторов содержит одинаковую часть, ее стоит вынести в константу и собирать дальше через String.format(). Я про часть "//*[@id='bottom_action-bac-phone_auth_form']"

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static final By SUPPORT_TEXT = By.xpath("//*[@id='bottom_action-bac-phone_auth_form']/form/p[1]");
можно ли к локатору привязаться не через порядковый номер элемента (касается так же констант GET_CODE_BTN и AGREEMENT_PERS_TEXT)? Добавят какой-то эелемент на страницу или поменяют местами и придется править

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
стоит подумать над названием. isPageOpened или например, isAllElementsDisplayed.

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
отсутствует пробел между () и {

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +public class LogAndReg {
отсутствует отступ между объявлением класса и содержимым класса

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +        return driver.findElement(MAIN_WINDOW).isDisplayed() &
стоит везде одинарный амперсант заменить на двойной, разница в этом форуме описана, где как лучше применять, почитай плиз https://ru.stackoverflow.com/questions/894602/и-и-их-братья-и-в-разных-ситуациях-Какие-у-них-различия

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/OfficePage.java
> +    public static final By OFFICE = By.xpath("//*[@id='ml']/div[3]/div/div/div/div[1]/div[2]/div[1]/h1");
отсутствует отступ между объявлением класса и содержимым класса

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/java/Pages/OfficePage.java
> +    public static final By OFFICE = By.xpath("//*[@id='ml']/div[3]/div/div/div/div[1]/div[2]/div[1]/h1");
локаторы просто пздц если честно))) надо поискать статью или чето такое как собирать локаторы

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/test/PageTest/OfficePageTest.java
> +import static Utils.WebDriverUtils.*;
я все вижу)))) исправь плиз

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/test/PageTest/OfficePageTest.java
> +    @BeforeMethod
отступ

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/test/PageTest/StartPageSiteTest.java
>      @BeforeMethod
отступ

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/test/PageTest/OfficePageTest.java
> +}
а где закрытие браузера?

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/test/PageTest/StartPageSiteTest.java
> +        assertTrue(isDisplay(OFFICE));
добавь везде меседжи в ассертах, касается всех тестовых классов

2023-12-25 16:24 UTC, Sanjaneo commented on src/main/test/PageTest/StartPageSiteTest.java
> +        assertTrue(isDisplay(OFFICE));
так же хорошей практикой будет если ты ассерты от остального тела метода будешь отступом отделять для читабельности

2023-12-25 16:24 UTC, Sanjaneo commented on .idea/workspace.xml
> +      <change beforePath="$PROJECT_DIR$/.idea/workspace.xml" beforeDir="false" afterPath="$PROJECT_DIR$/.idea/workspace.xml" afterDir="false" />
это ты тут в файле че такое нахерачил?

2023-12-25 16:30 UTC, Mornilius commented on .idea/workspace.xml
> +      <change beforePath="$PROJECT_DIR$/.idea/workspace.xml" beforeDir="false" afterPath="$PROJECT_DIR$/.idea/workspace.xml" afterDir="false" />
Я конфиг файлы пока не трогал, вроде бы

2023-12-25 16:31 UTC, Sanjaneo commented on .idea/workspace.xml
> +      <change beforePath="$PROJECT_DIR$/.idea/workspace.xml" beforeDir="false" afterPath="$PROJECT_DIR$/.idea/workspace.xml" afterDir="false" />
ну тогда почитай про gitIgnore и сделай такой файл чтобы всякая параша в ПРах не светилась

2023-12-26 17:40 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +public class LogAndReg {
Пофиксил названия классов

2023-12-26 17:41 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static final By MAIN_WINDOW = By.xpath("//*[@id='bottom_action']/div");
Дописал ко всем локаторам в конец "LOCATOR", должно быть, вроде как все понятно

2023-12-26 17:42 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static final By LOG_AND_REGISTRATION = By.xpath("//*[@id='bottom_action-bac-phone_auth_form']/form/h2");
Да, стоит так сделать, но я не везде юзал одинаковые локаторы, чтобы какую-то часть выносить в константу (экспериментировал с локаторами)

2023-12-26 17:45 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static final By SUPPORT_TEXT = By.xpath("//*[@id='bottom_action-bac-phone_auth_form']/form/p[1]");
Да, привязаться можно не к порядковому номеру (некоторые локаторы я делал через теги, более точные), писал выше, что занимался экспериментами с локаторами, а точнее с браузером (он мне сразу копировал рабочий xpath в виде порядкового номера, так было оч быстро)

2023-12-26 17:45 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
Ты прав, переименовал в твой вариант, он мне больше понравился

2023-12-26 17:48 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
фиксанул

2023-12-26 17:48 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +public class LogAndReg {
фиксанул

2023-12-26 17:49 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +        return driver.findElement(MAIN_WINDOW).isDisplayed() &
Заменил, но прочитав статью так и не очень понял разницу, еще буду гуглить

2023-12-26 17:49 UTC, Mornilius commented on src/main/java/Pages/OfficePage.java
> +    public static final By OFFICE = By.xpath("//*[@id='ml']/div[3]/div/div/div/div[1]/div[2]/div[1]/h1");
фикс

2023-12-26 17:50 UTC, Mornilius commented on src/main/java/Pages/OfficePage.java
> +    public static final By OFFICE = By.xpath("//*[@id='ml']/div[3]/div/div/div/div[1]/div[2]/div[1]/h1");
Знаю я как нормально это делать)
Как писал выше, подобный вариант мне браузер накинул, я решил затестить=)
А так, я понимаю, что это мрак вообще)

2023-12-26 17:51 UTC, Mornilius commented on src/main/test/PageTest/OfficePageTest.java
> +import static Utils.WebDriverUtils.*;
Это идеа сама так делает, когда больше 3 методов/констант пытаюсь импортить, не всегда замечаю, но сейчас пофиксил (вроде бы)

2023-12-26 17:52 UTC, Mornilius commented on src/main/test/PageTest/OfficePageTest.java
> +    @BeforeMethod
фикс

2023-12-26 17:52 UTC, Mornilius commented on src/main/test/PageTest/StartPageSiteTest.java
>      @BeforeMethod
фикс

2023-12-26 17:52 UTC, Mornilius commented on src/main/test/PageTest/OfficePageTest.java
> +}
Добавил

2023-12-26 17:52 UTC, Mornilius commented on src/main/test/PageTest/StartPageSiteTest.java
> +        assertTrue(isDisplay(OFFICE));
Отделил

2023-12-26 17:52 UTC, Mornilius commented on .idea/workspace.xml
> +      <change beforePath="$PROJECT_DIR$/.idea/workspace.xml" beforeDir="false" afterPath="$PROJECT_DIR$/.idea/workspace.xml" afterDir="false" />
Добавил workspace в gitignor

2023-12-26 18:01 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static final By LOG_AND_REGISTRATION = By.xpath("//*[@id='bottom_action-bac-phone_auth_form']/form/h2");
почему? у тебя эта часть которую я выделил используется в SUPPORT_TEXT_LOCATOR, GET_CODE_BTN_LOCATOR и в AGREEMENT_PERS_TEXT_LOCATOR. Но это не принципиальный момент, блочить ПР не буду по этому пункту

2023-12-26 18:02 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static final By SUPPORT_TEXT = By.xpath("//*[@id='bottom_action-bac-phone_auth_form']/form/p[1]");
ну ты поправишь то по итогу?)

2023-12-26 18:03 UTC, Sanjaneo commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
не вижу правки твоей по названию 
![Uploading image.png…]()

2023-12-26 18:05 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
Мы про метод говорим?

2023-12-26 18:06 UTC, Mornilius commented on src/main/java/Pages/LogAndReg.java
> +    public static boolean isDisplay(){
Да, заметил, в одном классе исправил, в другом нет, ща перепишу

2023-12-26 18:07 UTC, Sanjaneo commented on src/main/java/Pages/LoginAndRegistrationPage.java
> +public class LoginAndRegistrationPage{
пробел нужен между LoginAndRegistrationPage и {

2023-12-26 18:07 UTC, Sanjaneo commented on src/main/java/Pages/OfficePage.java
> +public class OfficePage{
пробел между OfficePage и {

2023-12-26 18:07 UTC, Sanjaneo commented on src/main/test/PageTest/OfficePageTest.java
> +import static Utils.WebDriverUtils.*;
так я же тебе вроде скидывал как проект настроить чтобы такого не было)

2023-12-26 18:19 UTC, Sanjaneo requested changes

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/test/PageTest/OfficePageTest.java
> +        timeOut();
думаю лучше будет  timeOut() добавить в метод startBrowser()? Если ты всегда хочешь после них таймаут оставлять

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/test/PageTest/OfficePageTest.java
> +public class OfficePageTest{
отступ

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/java/Pages/SchoolPage.java
> +public class SchoolPage{
отступ

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/java/Pages/StartSitePage.java
> +public class StartSitePage{
отступ

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/java/Pages/StartSitePage.java
> +    ////*[@id='ml2_header']/div[2]/div/div[1]/div/a[1]
комменты нужны тебе эти?

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/java/Utils/WebDriverUtils.java
> +public class WebDriverUtils{
отступ

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/test/PageTest/StartSitePageTest.java
> +public class StartSitePageTest{
отступ

2023-12-26 18:19 UTC, Sanjaneo commented on src/main/test/PageTest/StartSitePageTest.java
> +        assertEquals(getResponseCode(), 200);
не совсем понимаю смысл проверки на респонс код фронтовых автотестов. ты же в этом проекте и в этих тестах проверяешь фронт а не бэк. Типо понимаю если бы ты дергал ручку какую-то, смотрел уже на ее респонс, респонс код и прочее, но тут смысла особо не понял. Если как тренировка, то как говорил Олег Тиньков, сомнительно, но окэй

2023-12-26 18:49 UTC, Mornilius commented on src/main/test/PageTest/StartSitePageTest.java
> +public class StartSitePageTest{
фикс

2023-12-26 18:49 UTC, Mornilius commented on src/main/java/Utils/WebDriverUtils.java
> +public class WebDriverUtils{
фикс

2023-12-26 18:50 UTC, Mornilius commented on src/main/java/Pages/StartSitePage.java
> +    ////*[@id='ml2_header']/div[2]/div/div[1]/div/a[1]
Нет, удалил

2023-12-26 18:50 UTC, Mornilius commented on src/main/java/Pages/StartSitePage.java
> +public class StartSitePage{
фикс

2023-12-26 18:50 UTC, Mornilius commented on src/main/java/Pages/SchoolPage.java
> +public class SchoolPage{
фикс

2023-12-26 18:50 UTC, Mornilius commented on src/main/test/PageTest/OfficePageTest.java
> +public class OfficePageTest{
фикс

2023-12-26 18:51 UTC, Mornilius commented on src/main/test/PageTest/OfficePageTest.java
> +        timeOut();
Думал над этим, но не знаю потребуется ли он в дальнейшем т.к. не весь функционал сайта еще облазил

2023-12-26 18:51 UTC, Mornilius commented on src/main/java/Pages/OfficePage.java
> +public class OfficePage{
фикс

2023-12-26 18:51 UTC, Mornilius commented on src/main/java/Pages/LoginAndRegistrationPage.java
> +public class LoginAndRegistrationPage{
фикс

2023-12-26 18:53 UTC, Mornilius commented on src/main/test/PageTest/StartSitePageTest.java
> +        assertEquals(getResponseCode(), 200);
![Первый тест](https://github.com/Mornilius/QA-bookvoed/assets/121147303/8016f015-527c-4db0-8099-02ada77e4fbb)
![Второй тест](https://github.com/Mornilius/QA-bookvoed/assets/121147303/9edf341e-47e0-4140-87e9-1d1b4c6939c0)
Да, как тренировка, мне было интересно как это реализовать и юзать в дальнейшем можно 
Скрины прикрепил, надеюсь, что в таком виде нормально, если нет, то лучше тыкни меня, ибо я не понимаю как по-другому)

2023-12-27 06:32 UTC, Sanjaneo commented on src/main/test/PageTest/StartSitePageTest.java
> +        assertEquals(getResponseCode(), 200);
в таком виде сойдет, но в следующий раз если ты изменения делаешь для нескольких тестовых классов, то по-хорошему бы одним прогоном это все сделать. Настроить запуск сьюты например, почитать про настройку запусков через мавен или через файл настройки testNG (Junit)

2023-12-27 06:35 UTC, Sanjaneo requested changes

2023-12-27 06:35 UTC, Sanjaneo commented on src/main/java/Pages/LoginAndRegistrationPage.java
> +    public static boolean ElementsIsDisplayed() {
название методов с маленькой буквы

2023-12-27 06:35 UTC, Sanjaneo commented on src/main/java/Pages/LoginAndRegistrationPage.java
> +    public static boolean ElementsIsDisplayed() {
ну и порядок слов странный. isElementsDisplayed если уже такое название выбрал

2023-12-27 14:19 UTC, Mornilius commented on src/main/java/Pages/LoginAndRegistrationPage.java
> +    public static boolean ElementsIsDisplayed() {
сделал

2023-12-28 06:34 UTC, Sanjaneo approved these changes

2023-12-28 06:35 UTC, merged